CREATE TABLE `STOCK_MASTER` (
  ID int(11) unsigned NOT NULL AUTO_INCREMENT,
  SCRIPT varchar(50),
  NAME varchar(255),
  CAP varchar(50),
  SECTORE varchar(255),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;


CREATE TABLE `DAILY_UPDATE` (
  ID int(11) unsigned NOT NULL AUTO_INCREMENT,
  STOCK_ID int(11),
  BSE_PRICE DOUBLE(10,4),
  NSE_PRICE DOUBLE(10,4),
  DAY_HEIGH DOUBLE(10,4),
  DAY_LOW DOUBLE(10,4),
  PREVIOUS_CLOSE DOUBLE(10,4),
  CHAGE DOUBLE(5,2),
  CREATED_ON datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(50),
  MODIFIED_ON datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  MODIFIED_BY VARCHAR(50),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;
